### ISSUE TITLE
False Positive Report

### ISSUE THREAD

**Issue by DRSDavidSoft** [S8D/AdBlock#1]
Hi,

the following domains names are not ads/trackers, and should not be blocked:

### description
- `openload.co`: popular file-sharing website
- `i.scdn.co`: image serving for the Spotify music streaming app
- `bitly.com`: link shortening service
- `disqus.com`: comment service for major blogs/sites
- `duckduckgo.com`: popular search-engine, a privacy-oriented alternative to Google
- `vk.com`: popular Russian social website, equivalent to Facebook
- `placehold.it`: image placeholders often used during web design
- `mail.ru`: popular Russian email service, equivalent to gmail

**Comment by S8D** [comment]
You can use this filter with NanoBlock (FireFox/Chrome).

**Comment by S8D** [comment]
Ok
